title: Min Kaung Khant
logo: /assets/img/CircleProfile.png
description: **Phone:** [+971529457731](https://wa.me/971529457731)
**Email:** [minkaungkhant.k2@gmail.com](mailto:minkaungkhant.k2@gmail.com)
**LinkedIn:** [LinkedIn](https://www.linkedin.com/in/min-kaung-khant/)
**Location:** Dubai, UAE
show_downloads: true
theme: jekyll-theme-minimal
